// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: geekedu.proto

package geekedu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GeekEduService_Register_FullMethodName        = "/geekedu.GeekEduService/Register"
	GeekEduService_UserLogin_FullMethodName       = "/geekedu.GeekEduService/UserLogin"
	GeekEduService_GetCourseList_FullMethodName   = "/geekedu.GeekEduService/GetCourseList"
	GeekEduService_CreateCourse_FullMethodName    = "/geekedu.GeekEduService/CreateCourse"
	GeekEduService_UploadVideo_FullMethodName     = "/geekedu.GeekEduService/UploadVideo"
	GeekEduService_CreateOrder_FullMethodName     = "/geekedu.GeekEduService/CreateOrder"
	GeekEduService_GetCourseVideos_FullMethodName = "/geekedu.GeekEduService/GetCourseVideos"
	GeekEduService_GetVideoPlayUrl_FullMethodName = "/geekedu.GeekEduService/GetVideoPlayUrl"
)

// GeekEduServiceClient is the client API for GeekEduService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeekEduServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	GetCourseList(ctx context.Context, in *CourseListRequest, opts ...grpc.CallOption) (*CourseListResponse, error)
	CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error)
	UploadVideo(ctx context.Context, in *UploadVideoRequest, opts ...grpc.CallOption) (*UploadVideoResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetCourseVideos(ctx context.Context, in *GetCourseVideosRequest, opts ...grpc.CallOption) (*GetCourseVideosResponse, error)
	GetVideoPlayUrl(ctx context.Context, in *GetVideoPlayUrlRequest, opts ...grpc.CallOption) (*GetVideoPlayUrlResponse, error)
}

type geekEduServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeekEduServiceClient(cc grpc.ClientConnInterface) GeekEduServiceClient {
	return &geekEduServiceClient{cc}
}

func (c *geekEduServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, GeekEduService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, GeekEduService_UserLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) GetCourseList(ctx context.Context, in *CourseListRequest, opts ...grpc.CallOption) (*CourseListResponse, error) {
	out := new(CourseListResponse)
	err := c.cc.Invoke(ctx, GeekEduService_GetCourseList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error) {
	out := new(CreateCourseResponse)
	err := c.cc.Invoke(ctx, GeekEduService_CreateCourse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) UploadVideo(ctx context.Context, in *UploadVideoRequest, opts ...grpc.CallOption) (*UploadVideoResponse, error) {
	out := new(UploadVideoResponse)
	err := c.cc.Invoke(ctx, GeekEduService_UploadVideo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, GeekEduService_CreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) GetCourseVideos(ctx context.Context, in *GetCourseVideosRequest, opts ...grpc.CallOption) (*GetCourseVideosResponse, error) {
	out := new(GetCourseVideosResponse)
	err := c.cc.Invoke(ctx, GeekEduService_GetCourseVideos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) GetVideoPlayUrl(ctx context.Context, in *GetVideoPlayUrlRequest, opts ...grpc.CallOption) (*GetVideoPlayUrlResponse, error) {
	out := new(GetVideoPlayUrlResponse)
	err := c.cc.Invoke(ctx, GeekEduService_GetVideoPlayUrl_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeekEduServiceServer is the server API for GeekEduService service.
// All implementations must embed UnimplementedGeekEduServiceServer
// for forward compatibility
type GeekEduServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	GetCourseList(context.Context, *CourseListRequest) (*CourseListResponse, error)
	CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error)
	UploadVideo(context.Context, *UploadVideoRequest) (*UploadVideoResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetCourseVideos(context.Context, *GetCourseVideosRequest) (*GetCourseVideosResponse, error)
	GetVideoPlayUrl(context.Context, *GetVideoPlayUrlRequest) (*GetVideoPlayUrlResponse, error)
	mustEmbedUnimplementedGeekEduServiceServer()
}

// UnimplementedGeekEduServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeekEduServiceServer struct {
}

func (UnimplementedGeekEduServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGeekEduServiceServer) UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedGeekEduServiceServer) GetCourseList(context.Context, *CourseListRequest) (*CourseListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseList not implemented")
}
func (UnimplementedGeekEduServiceServer) CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedGeekEduServiceServer) UploadVideo(context.Context, *UploadVideoRequest) (*UploadVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedGeekEduServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedGeekEduServiceServer) GetCourseVideos(context.Context, *GetCourseVideosRequest) (*GetCourseVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseVideos not implemented")
}
func (UnimplementedGeekEduServiceServer) GetVideoPlayUrl(context.Context, *GetVideoPlayUrlRequest) (*GetVideoPlayUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoPlayUrl not implemented")
}
func (UnimplementedGeekEduServiceServer) mustEmbedUnimplementedGeekEduServiceServer() {}

// UnsafeGeekEduServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeekEduServiceServer will
// result in compilation errors.
type UnsafeGeekEduServiceServer interface {
	mustEmbedUnimplementedGeekEduServiceServer()
}

func RegisterGeekEduServiceServer(s grpc.ServiceRegistrar, srv GeekEduServiceServer) {
	s.RegisterService(&GeekEduService_ServiceDesc, srv)
}

func _GeekEduService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_UserLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_GetCourseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).GetCourseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_GetCourseList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).GetCourseList(ctx, req.(*CourseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_CreateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).CreateCourse(ctx, req.(*CreateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_UploadVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).UploadVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_UploadVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).UploadVideo(ctx, req.(*UploadVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_GetCourseVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).GetCourseVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_GetCourseVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).GetCourseVideos(ctx, req.(*GetCourseVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_GetVideoPlayUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoPlayUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).GetVideoPlayUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_GetVideoPlayUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).GetVideoPlayUrl(ctx, req.(*GetVideoPlayUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeekEduService_ServiceDesc is the grpc.ServiceDesc for GeekEduService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeekEduService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geekedu.GeekEduService",
	HandlerType: (*GeekEduServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GeekEduService_Register_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _GeekEduService_UserLogin_Handler,
		},
		{
			MethodName: "GetCourseList",
			Handler:    _GeekEduService_GetCourseList_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _GeekEduService_CreateCourse_Handler,
		},
		{
			MethodName: "UploadVideo",
			Handler:    _GeekEduService_UploadVideo_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _GeekEduService_CreateOrder_Handler,
		},
		{
			MethodName: "GetCourseVideos",
			Handler:    _GeekEduService_GetCourseVideos_Handler,
		},
		{
			MethodName: "GetVideoPlayUrl",
			Handler:    _GeekEduService_GetVideoPlayUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geekedu.proto",
}
